# Generated by Django 3.2.7 on 2021-10-01 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_rename_name_genre_genre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likes',
            old_name='product',
            new_name='movie',
        ),
    ]
